env:
  ENV: development
  AWS_REGION: ap-northeast-2
  CONTAINER_NAME: container-test-demo
  ECS_CLUSTER_NAME: ecs-cluster-test
  ECS_SERVICE_NAME: ecs-service
  ECR_REPOSITORY_NAME: ecr-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Demo CI on ECR

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ecr-test
          IMAGE_TAG: ${{ github. sha }}
        run: |
          # Build a docker container and push it to ECR
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
      
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ./task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE_NAME }}
          cluster: ${{ env.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true
    
      - name: Send Slack Message
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Monitoring_bot_dev
          fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
          mention: here
          if_mention: failure, cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always()  # Pick up events even if the job fails or is canceled.
  
  # slackNotify:
  #   if: ${{ always() }}
  #   needs: deploy
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - name: Notifiy message to slack
  #       uses: rtCamp/action-slack-notify@v2
  #       with:
  #         status: ${{ needs.deploy.result }}
  #       env:
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  #         SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
  #         # SLACK_COLOR: ${{ job.status }} # 또는 'green', '#ff00ff' 처럼 직접 색상 지정
  #         SLACK_USERNAME: Github CI
  #         SLACK_ICON: https://st2.depositphotos.com/2274151/11073/v/950/depositphotos_110731914-stock-illustration-failed-red-grunge-round-vintage.jpg
  #         SLACK_TITLE: Message
  #         SLACK_MESSAGE: 'deploy 실패 :boom:'